"""Response dataclass -- output of IntentEngine.generate_response()."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Response:
    """Output of ``IntentEngine.generate_response()``.

    Contains the LLM-generated response text and the emotion label to
    apply during TTS synthesis.
    """

    text: str
    """Response text generated by the LLM."""

    emotion: str
    """Emotion to apply in TTS synthesis."""
