"""Response dataclass -- output of IntentEngine.generate_response()."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Response:
    """Output of ``IntentEngine.generate_response()``.

    Contains the LLM-generated response text, the emotion label to
    apply during TTS synthesis, and the intent the LLM parsed from the
    user's input.
    """

    text: str
    """Response text generated by the LLM."""

    emotion: str
    """Emotion to apply in TTS synthesis."""

    intent: str | None = None
    """User intent parsed by the LLM (e.g. ``"delete_files"``), or ``None``.

    This is what to pass to ``IntentEngine.evaluate_intent()``.
    """
